name: Documentation Generation

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # or any other branch you want to target
  pull_request:
    branches: [ main ]  # or any other branch you want to target

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        
      - name: List all changed files
        run: |
          python .github/scripts/generate_documentation.py --files ${{ steps.changed-files.outputs.all_changed_files }}