name: Documentation Generation

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # or any other branch you want to target
  pull_request:
    branches: [ main ]  # or any other branch you want to target

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai GitPython

    - name: Get changed files
      id: files
      run: |
        git fetch origin ${{ github.base_ref }}
        echo "Changed files:"
        git diff --name-only origin/${{ github.base_ref }} ${{ github.event.pull_request.head.sha }}

    # - name: Get list of changed files
    #   id: files
    #   run: |
    #     echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})" >> $GITHUB_ENV


    # - name: Run documentation script
    #   env:
    #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    #   run: |
    #     python .github/scripts/generate_documentation.py